apiVersion: 1
prune: true
deleteDatasources:
  - name: Loki
    orgId: 1
datasources:
  - name: Loki
    uid: dffkjmh70zr40c
    type: loki
    access: proxy
    url: http://obs-loki:3100
    editable: true
